name:                chaos-maps
version:             0.1.0.0
github:              "febouge/chaos-maps"
license:             GPL-3
license-file:        LICENSE
author:              "Ferran"
maintainer:          "example@example.com"
copyright:           "2018 Ferran"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/febouge/chaos-maps#readme>

dependencies:
- base >= 4.7 && < 5
- Chart >= 1.8.3
- Chart-cairo >= 1.8.3
- Chart-diagrams >= 1.8.3
- optparse-applicative >= 0.14.2.0
- text >= 1.2.3.0

library:
  source-dirs: src

executables:
  chaos-maps-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - chaos-maps

tests:
  chaos-maps-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - chaos-maps
    - hspec
